version: "3"
services:
  postgres:
            image: postgres:latest
            container_name: postgres
            ports:
                - "5432:5432"
            environment:
              POSTGRES_PASSWORD: 12345
              POSTGRES_USER: postgres
              POSTGRES_DB: loizenaidb
  backend:
        build: ./backend
        container_name: backend
        environment:
         DATABASE: loizenaidb
         USERNAME: postgres
         PASSWORD: 12345
         HOST: postgres
        ports:
            - "8080:8080"
  frontend:
        build: ./frontend
        container_name: frontend
        stdin_open: true
        environment:
           - BACKEND_URL=http://backend:8080
        ports:
             - "3000:3000"
