version: "3"
services:
  postgres:
            image: postgres:latest
            container_name: postgres
            ports:
                - "5432:5432"
            environment:
              POSTGRES_PASSWORD: 123456
              POSTGRES_USER: postgres
              POSTGRES_DB: loizenaidb
  backend:
#        build: ./backend
        image: naveen5035/backend:v9
        container_name: backend        
        environment:
         DATABASE: loizenaidb
         USERNAME: postgres
         PASSWORD: 123456
         HOST: postgres
        ports:
            - "8080:8080"   
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;'   
  frontend:
#        build: ./frontend
        image: naveen5035/frontend:v9
        container_name: frontend
        stdin_open: true
        environment:
            BACKEND_URL: http://backend:8080
        ports:
             - "3000:3000"
